name: CrystalStrike
version: 0.2
description: Get loot when lightning strikes!
authors: [dellman135, _stevoism_, jflory7, Ephesus]
website: https://github.com/CrystalCraftMC/CrystalStrike
main: com.crystalcraftmc.crystalstrike.CrystalStrike
api-version: 1.13